@echo off
echo 📁 Adding .gitkeep files to all folders...

mkdir "%~dp0core-theory"
type nul > "%~dp0core-theory\.gitkeep"
mkdir "%~dp0mathematics\abc-conjecture"
type nul > "%~dp0mathematics\abc-conjecture\.gitkeep"
mkdir "%~dp0mathematics\beal-conjecture"
type nul > "%~dp0mathematics\beal-conjecture\.gitkeep"
mkdir "%~dp0mathematics\riemann-hypothesis"
type nul > "%~dp0mathematics\riemann-hypothesis\.gitkeep"
mkdir "%~dp0mathematics\yang-mills"
type nul > "%~dp0mathematics\yang-mills\.gitkeep"
mkdir "%~dp0physics\quantum-gravity"
type nul > "%~dp0physics\quantum-gravity\.gitkeep"
mkdir "%~dp0physics\protein-folding"
type nul > "%~dp0physics\protein-folding\.gitkeep"
mkdir "%~dp0physics\unified-field"
type nul > "%~dp0physics\unified-field\.gitkeep"
mkdir "%~dp0consciousness\dna-interface"
type nul > "%~dp0consciousness\dna-interface\.gitkeep"
mkdir "%~dp0consciousness\emergence"
type nul > "%~dp0consciousness\emergence\.gitkeep"
mkdir "%~dp0consciousness\rai-ray"
type nul > "%~dp0consciousness\rai-ray\.gitkeep"
mkdir "%~dp0code\vgt-core"
type nul > "%~dp0code\vgt-core\.gitkeep"
mkdir "%~dp0code\tests"
type nul > "%~dp0code\tests\.gitkeep"
mkdir "%~dp0code\simulations"
type nul > "%~dp0code\simulations\.gitkeep"
mkdir "%~dp0code\analysis"
type nul > "%~dp0code\analysis\.gitkeep"
mkdir "%~dp0code\examples"
type nul > "%~dp0code\examples\.gitkeep"
mkdir "%~dp0notebooks\tutorials"
type nul > "%~dp0notebooks\tutorials\.gitkeep"
mkdir "%~dp0notebooks\research"
type nul > "%~dp0notebooks\research\.gitkeep"
mkdir "%~dp0notebooks\visualizations"
type nul > "%~dp0notebooks\visualizations\.gitkeep"
mkdir "%~dp0papers\drafts"
type nul > "%~dp0papers\drafts\.gitkeep"
mkdir "%~dp0papers\submitted"
type nul > "%~dp0papers\submitted\.gitkeep"
mkdir "%~dp0papers\published"
type nul > "%~dp0papers\published\.gitkeep"
mkdir "%~dp0docs\_layouts"
type nul > "%~dp0docs\_layouts\.gitkeep"
mkdir "%~dp0docs\assets"
type nul > "%~dp0docs\assets\.gitkeep"
mkdir "%~dp0docs\api"
type nul > "%~dp0docs\api\.gitkeep"
mkdir "%~dp0docs\tutorials"
type nul > "%~dp0docs\tutorials\.gitkeep"
mkdir "%~dp0.github\workflows"
type nul > "%~dp0.github\workflows\.gitkeep"
mkdir "%~dp0data"
type nul > "%~dp0data\.gitkeep"
mkdir "%~dp0results"
type nul > "%~dp0results\.gitkeep"
mkdir "%~dp0figures"
type nul > "%~dp0figures\.gitkeep"

echo ✅ All .gitkeep files created.
pause
